### PR TITLE
Command tests

### PR DESCRIPTION
**Pull request by bosunski**
Pull Request for Issue #4   .

### Summary of Changes
Added the Command Class

### Testing Instructions
Run php cli/joomla.php check-update

### Expected result

Tells whether there is a new update or not.

### Actual result
` ! [NOTE] New Joomla Version 4.0.0-alpha4-dev is available.`

OR 

`[OK] You already have the latest Joomla version 4.0.0-alpha4-dev`

### CODE REVIEW

**Comment by bosunski** [comment]
@alikon this is the first PR for check-updates

**Comment by bosunski** [comment]
Quite Hard and really seem impossible writing Test for the command because We need the app container, which (I'm not sure though) I think is not available when phpunit is running
@rjcf18 @mbabker @wilsonge 
Tried @wilsonge method but it's not working.

**Comment by bosunski** [comment]
Alright. I will update that.

What other things should I take in for consideration

**Comment by alikon** [comment]
we discuss this on today meeting ;)

**Comment by bosunski** [comment]
@alikon Check latest commit

**Comment by alikon** [comment]
cs should be ok now or at lest travis&drone don't complain

but we have too much files changed (8) , shouldn't they be only 2, at least before the TDD part ?

**Comment by bosunski** [comment]
Yes. I don't really know why other files changed @alikon.

**Comment by bosunski** [comment]
@alikon check out the new commit [here](https://github.com/joomla-projects/gsoc18_cli_update/pull/5/commits/da37f641b751b34ee6481c03128292993ba91766)

**Comment by alikon** [comment]
Quite hard to check 604 files ;)

Il ven 25 mag 2018, 02:40 Egberinde Olatunbosun <notifications@github.com>
ha scritto:

**Comment by bosunski** [comment]
The 604 files are because I ran `composer install` and I've fixed that now, my last commit contains the the only files affected. That's why I'm referring to it so you can check [here](https://github.com/joomla-projects/gsoc18_cli_update/pull/5/commits/da37f641b751b34ee6481c03128292993ba91766)

**Comment by alikon** [comment]
close in favour of #6

**Pull request closed without merging**
